spring.application.name=Projektarbeit_Modul295_Vincent_Diergardt
spring.datasource.url=JDBC:mysql://127.0.0.1:3306/airdatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Zurich
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
